version: "3.9"

volumes:
  my-db:

networks:
  pg-network:

services:
  postgres:
    container_name: pg_container
    image: postgres:14-alpine
    networks:
      - pg-network
    ports:
      - 5432:5432
    volumes:
      - my-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=test_db
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    networks:
      - pg-network
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
